nama=input("MASUKAN NAMA ANDA= ")
umur=int(input("UMUR = "))
alamat=input("ALAMAT = ")
lulusan=input("LULUSAN = ")
agama=input("AGAMA = ")
nim=input("NIM = ")
tgl=input("TANGGAL LAHIR = ")

print("=="*10)
print("|   NAMA      :", nama    )
print("|   NIM       :", nim     )
print("|   UMUR      :", umur    )
print("|   TGL LAHIR :", tgl    )
print("|   ALAMAT    :", alamat  )
print("|   AGAMA     :", agama   )
print("|   LULUSAN   :", lulusan )
print("=="*10)
